version: '3.8'
services:
  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    command: npm run start:debug
    env_file:
      - ./.env.development
    ports:
      - '3000:3000'

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./db/redis:/root/redis
      - ./db/redis.conf:/var/lib/redis/redis.conf
    environment:
      - REDIS_PASSWORD=123456
      - REDIS_PORT=6379
      - REDIS_DATABASES=16